spring.application.name=todolist

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

#Database
spring.datasource.url=jdbc:mariadb://localhost:3306/todolist?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = root
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver